#!/bin/bash

SLACK_AUTH_TOKEN=""
RECIPIENTS=""
FILENAME=""
TITLE=""
FOOTER=""

usage() { echo "Usage: $(basename "$0") [options] <file>

Options:
    -r <channel names|channel IDs>
    -n <file name>
    -t <title text>
    -f <initial comment>
    -T <authentication token>

Examples:
    $(basename "$0") somefile.jpg
    $(basename "$0") -r general -n \"filename.log\" somefile.txt
    ps | $(basename "$0") -r C8P15L0TV -t \"\$(id -un) \$(hostname -f)\"
    ls -la /etc/ | $(basename "$0") -r D024BE91L,random -f \"\$(history 1)\"
" 1>&2; exit 1; }

while getopts ":r:n:t:f:T:" o; do
    case "${o}" in
        r)
            RECIPIENTS="${OPTARG}"
            ;;
        n)
            FILENAME="${OPTARG}"
            ;;
        t)
            TITLE="${OPTARG}"
            ;;
        f)
            FOOTER="${OPTARG}"
            ;;
        T)
            SLACK_AUTH_TOKEN="${OPTARG}"
            ;;
        *)
            echo "Illegal option: ${OPTARG}"$'\n'
            usage
            ;;
    esac
done
shift $((OPTIND-1))

if [[ "$SLACK_AUTH_TOKEN" == "" ]]; then
    echo "No authentication token specified. Please set SLACK_AUTH_TOKEN in $(readlink -f "$0") or use the -T option."$'\n'
    usage
fi

options=""
if [[ ! -z "$RECIPIENTS" ]]; then
    options="$options --form-string channels=\"\$RECIPIENTS\""
fi

if [[ ! -z "$FILENAME" ]]; then
    options="$options --form-string filename=\"\$FILENAME\""
fi

if [[ ! -z "$TITLE" ]]; then
    options="$options --form-string title=\"\$TITLE\""
fi

if [[ ! -z "$FOOTER" ]]; then
    options="$options --form-string initial_comment=\"\$FOOTER\""
fi

filepath=$*
if [[ "$filepath" == "" ]]; then
    if [ -t 0 ]; then
        echo "No file specified"$'\n'
        usage
    else
        text=""
        while IFS= read -r line || [ -n "$line" ]; do
            text="$text$line"$'\n'
        done
        payload="--form-string content=\"\$text\""
    fi
else
    payload="-F file=@\"\$filepath\""
fi

eval "curl -s -S $payload$options --form-string token=\"\$SLACK_AUTH_TOKEN\" --form-string pretty=true https://slack.com/api/files.upload 2>&1" 
